package com.wms.factory;

import com.wms.model.InventoryItem;
import com.wms.model.Order;
import com.wms.repository.InventoryDAO;
import com.wms.repository.OrderDAO;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.UUID;

/**
 * DESIGN PATTERN: Factory Method Pattern
 * 
 * Creates different types of reports based on the requested type
 * without exposing creation logic to the client code.
 * 
 * How it works:
 *   1. Client calls ReportFactory.createReport(type, generatedBy)
 *   2. Factory determines which concrete Report subclass to instantiate
 *   3. New report types can be added by creating a new class and
 *      updating the switch — no other code changes needed (Open/Closed)
 * 
 * Report Types:
 *   - INVENTORY: Current stock levels across all warehouse zones
 *   - ORDER: Summary of all orders with status breakdown
 *   - LOW_STOCK: Items below minimum stock threshold
 */
public class ReportFactory {

    public static final String TYPE_INVENTORY = "Inventory Report";
    public static final String TYPE_ORDER = "Order Report";
    public static final String TYPE_LOW_STOCK = "Low Stock Report";

    /**
     * Factory method — creates the appropriate report based on type.
     * @param reportType the type of report to generate
     * @param generatedBy the username generating the report
     * @return formatted report content as a String
     */
    public static String createReport(String reportType, String generatedBy) {
        String timestamp = LocalDateTime.now().format(
                DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        String reportId = "RPT-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();

        switch (reportType) {
            case TYPE_INVENTORY:
                return generateInventoryReport(reportId, generatedBy, timestamp);
            case TYPE_ORDER:
                return generateOrderReport(reportId, generatedBy, timestamp);
            case TYPE_LOW_STOCK:
                return generateLowStockReport(reportId, generatedBy, timestamp);
            default:
                throw new IllegalArgumentException("Unknown report type: " + reportType);
        }
    }

    // ── Concrete Report: Inventory ─────────────────────────────
    private static String generateInventoryReport(String id, String by, String time) {
        InventoryDAO dao = new InventoryDAO();
        List<InventoryItem> items = dao.findAll();

        StringBuilder sb = new StringBuilder();
        sb.append("═══════════════════════════════════════════════════════════════\n");
        sb.append("  WAREHOUSE INVENTORY REPORT\n");
        sb.append("  Report ID: ").append(id).append("\n");
        sb.append("  Generated by: ").append(by).append("  |  Date: ").append(time).append("\n");
        sb.append("═══════════════════════════════════════════════════════════════\n\n");

        sb.append(String.format("%-10s %-26s %-8s %-22s %-12s%n",
                "ID", "Product", "Qty", "Location", "Status"));
        sb.append("─".repeat(80)).append("\n");

        int totalUnits = 0;
        for (InventoryItem item : items) {
            sb.append(String.format("%-10s %-26s %-8d %-22s %-12s%n",
                    item.getItemId(), item.getProductName(), item.getQuantity(),
                    item.getStorageLocation(), item.getStatus()));
            totalUnits += item.getQuantity();
        }

        sb.append("─".repeat(80)).append("\n");
        sb.append("Total Products: ").append(items.size());
        sb.append("  |  Total Units: ").append(totalUnits).append("\n");
        return sb.toString();
    }

    // ── Concrete Report: Order Summary ─────────────────────────
    private static String generateOrderReport(String id, String by, String time) {
        OrderDAO dao = new OrderDAO();
        List<Order> orders = dao.findAll();

        StringBuilder sb = new StringBuilder();
        sb.append("═══════════════════════════════════════════════════════════════\n");
        sb.append("  ORDER SUMMARY REPORT\n");
        sb.append("  Report ID: ").append(id).append("\n");
        sb.append("  Generated by: ").append(by).append("  |  Date: ").append(time).append("\n");
        sb.append("═══════════════════════════════════════════════════════════════\n\n");

        sb.append(String.format("%-10s %-20s %-22s %-6s %-12s %-9s%n",
                "ID", "Client", "Product", "Qty", "Status", "Type"));
        sb.append("─".repeat(82)).append("\n");

        long pending = 0, processing = 0, completed = 0;
        for (Order o : orders) {
            sb.append(String.format("%-10s %-20s %-22s %-6d %-12s %-9s%n",
                    o.getOrderId(), o.getClientName(), o.getProductName(),
                    o.getQuantity(), o.getStatus(), o.getOrderType()));
            if ("Pending".equals(o.getStatus())) pending++;
            else if ("Processing".equals(o.getStatus())) processing++;
            else if ("Completed".equals(o.getStatus())) completed++;
        }

        sb.append("─".repeat(82)).append("\n");
        sb.append("Pending: ").append(pending).append("  |  Processing: ").append(processing);
        sb.append("  |  Completed: ").append(completed).append("\n");
        return sb.toString();
    }

    // ── Concrete Report: Low Stock Alert ───────────────────────
    private static String generateLowStockReport(String id, String by, String time) {
        InventoryDAO dao = new InventoryDAO();
        List<InventoryItem> lowStock = dao.findLowStockItems();

        StringBuilder sb = new StringBuilder();
        sb.append("═══════════════════════════════════════════════════════════════\n");
        sb.append("  LOW STOCK ALERT REPORT\n");
        sb.append("  Report ID: ").append(id).append("\n");
        sb.append("  Generated by: ").append(by).append("  |  Date: ").append(time).append("\n");
        sb.append("═══════════════════════════════════════════════════════════════\n\n");

        if (lowStock.isEmpty()) {
            sb.append("✓ All items are adequately stocked. No alerts.\n");
        } else {
            sb.append(String.format("%-10s %-26s %-8s %-22s %-12s%n",
                    "ID", "Product", "Qty", "Location", "Status"));
            sb.append("─".repeat(80)).append("\n");
            for (InventoryItem item : lowStock) {
                sb.append(String.format("%-10s %-26s %-8d %-22s %-12s%n",
                        item.getItemId(), item.getProductName(), item.getQuantity(),
                        item.getStorageLocation(), item.getStatus()));
            }
            sb.append("\n⚠ ACTION REQUIRED: ").append(lowStock.size());
            sb.append(" item(s) need immediate restocking.\n");
        }
        return sb.toString();
    }
}
